apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Azure resources
  AZURE_RESOURCE_GROUP: "your-resource-group"
  AZURE_VMSS_NAME: "your-vmss-name"
  
  # Ollama Configuration
  OLLAMA_API_URL: "http://ollama-service:11434"
  OLLAMA_MODEL: "llama3:8b"
  OLLAMA_FALLBACK_MODEL: "mistral:7b"
  SCALING_CONFIDENCE_THRESHOLD: "0.7"
  
  # Application settings
  MIN_INSTANCES: "2"
  MAX_INSTANCES: "10"
  SCALING_COOLDOWN_MINUTES: "15"
  METRICS_LOOKBACK_HOURS: "1"
  METRICS_INTERVAL_MINUTES: "15" 