apiVersion: v1
kind: Service
metadata:
  name: dynamic-infrastructure-scaling
  labels:
    app: dynamic-infrastructure-scaling
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: dynamic-infrastructure-scaling 